# Generated by Django 3.1.5 on 2021-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id', 'is_done'],
            },
        ),
    ]
